// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlYuYlLiLSv_OG_4otaSdK6-XFrSBwHhw',
    appId: '1:743816422249:web:3aae79129d54261de3d3f8',
    messagingSenderId: '743816422249',
    projectId: 'app-postura-7bb04',
    authDomain: 'app-postura-7bb04.firebaseapp.com',
    storageBucket: 'app-postura-7bb04.firebasestorage.app',
    measurementId: 'G-9KG3TCK1K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAyvDS1G5bNifWX-EAiYQGUBBlrtEGCn0',
    appId: '1:743816422249:android:84a1e4fe037a0bc6e3d3f8',
    messagingSenderId: '743816422249',
    projectId: 'app-postura-7bb04',
    storageBucket: 'app-postura-7bb04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACqN98PXBP6uP4jpoV8m307WzjaUbFvVY',
    appId: '1:743816422249:ios:921d1e461cba1de7e3d3f8',
    messagingSenderId: '743816422249',
    projectId: 'app-postura-7bb04',
    storageBucket: 'app-postura-7bb04.firebasestorage.app',
    iosBundleId: 'com.example.recordatoriosPostura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACqN98PXBP6uP4jpoV8m307WzjaUbFvVY',
    appId: '1:743816422249:ios:921d1e461cba1de7e3d3f8',
    messagingSenderId: '743816422249',
    projectId: 'app-postura-7bb04',
    storageBucket: 'app-postura-7bb04.firebasestorage.app',
    iosBundleId: 'com.example.recordatoriosPostura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlYuYlLiLSv_OG_4otaSdK6-XFrSBwHhw',
    appId: '1:743816422249:web:7b02b9bd76dff60ee3d3f8',
    messagingSenderId: '743816422249',
    projectId: 'app-postura-7bb04',
    authDomain: 'app-postura-7bb04.firebaseapp.com',
    storageBucket: 'app-postura-7bb04.firebasestorage.app',
    measurementId: 'G-NZ5GEV40MY',
  );
}
